service: serverless-challenge
provider:
  name: aws
  runtime: nodejs16.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:GetFunction
      Resource:
        - arn:aws:dynamodb:::*
plugins:
  - serverless-offline

functions:
  getEmployees:
    handler: src/main/lambda-functions/employees.getEmployeeLambda
    events:
      - http:
          path: /employees
          method: get
          cors: true
