org: guilhermeais
app: serverless-challenge
service: serverless-challenge
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_ENV: production
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:GetFunction
      Resource:
        - arn:aws:dynamodb:sa-east-1:*:*
plugins:
  - serverless-offline

functions:
  getEmployees:
    handler: src/main/lambda-functions/employees.getEmployeeLambda
    events:
      - http:
          path: /employees
          method: get
          cors: true
      - http:
          path: /employees/{id}
          method: get
          cors: true